name: money_minder_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.2
  flutter_colorpicker: ^1.1.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.1
  uuid: ^4.5.1

  firebase_core: 2.32.0
  js: ^0.6.3

  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5

  expense_repository:
    path: packages/expense_repository
  firebase_auth: ^4.16.0
  firebase_auth_web: ^5.8.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

dependency_overrides:
  async: ^2.12.0
  characters: ^1.4.0
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  source_span: ^1.10.1
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  test_api: ^0.7.4
  vm_service: ^15.0.0
  boolean_selector: ^2.1.2
